fix: fix the if bash expression in the dockerfile

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -87,16 +87,19 @@ RUN chmod +x /tmp/symlink_clang_utils.sh \
     && /tmp/symlink_clang_utils.sh 21 \
     && rm /tmp/symlink_clang_utils.sh
 
-RUN rm /work/build_sym_link \
-    && if [ "$BUILD_PLATFORM" = "linux/riscv64" ]; then \
+RUN if [ -e "/work/build_sym_link" ]; then \
+    rm /work/build_sym_link; \ 
+    fi \
+    && \
+    if [ "$BUILD_PLATFORM" = "linux/riscv64" ]; then \
     ln -s /work/build_riscv /work/build_sym_link; \
-    elif [ "$BUILD_PLATFORM" = "linux/arm64/v8"] || [ "$BUILD_PLATFORM" = "linux/arm64"]; then \
+    elif [ "$BUILD_PLATFORM" = "linux/arm64/v8" ] || [ "$BUILD_PLATFORM" = "linux/arm64" ]; then \
     ln -s /work/build_arm64 /work/build_sym_link; \
-    elif [ "$BUILD_PLATFORM" = "linux/amd64"]; then \
+    elif [ "$BUILD_PLATFORM" = "linux/amd64" ]; then \
     ln -s /work/build /work/build_sym_link; \
     else \
-    echo "invalid BUILD_PLATFORM: $BUILD_PLATFORM" \ 
-    exit 2 \
+    echo "invalid BUILD_PLATFORM: $BUILD_PLATFORM"; \ 
+    exit 2; \
     fi
 
 
